#![doc = "Peripheral access API for LPC55S16 microcontrollers (generated using svd2rust v0.37.1 (29ad569 2025-10-19))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 3;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn WDT_BOD();
    fn DMA0();
    fn GINT0();
    fn GINT1();
    fn PIN_INT0();
    fn PIN_INT1();
    fn PIN_INT2();
    fn PIN_INT3();
    fn UTICK0();
    fn MRT0();
    fn CTIMER0();
    fn CTIMER1();
    fn SCT0();
    fn CTIMER3();
    fn FLEXCOMM0();
    fn FLEXCOMM1();
    fn FLEXCOMM2();
    fn FLEXCOMM3();
    fn FLEXCOMM4();
    fn FLEXCOMM5();
    fn FLEXCOMM6();
    fn FLEXCOMM7();
    fn ADC0();
    fn ACMP();
    fn USB0_NEEDCLK();
    fn USB0();
    fn RTC();
    fn PIN_INT4();
    fn PIN_INT5();
    fn PIN_INT6();
    fn PIN_INT7();
    fn CTIMER2();
    fn CTIMER4();
    fn OS_EVENT();
    fn CAN0_IRQ0();
    fn CAN0_IRQ1();
    fn USB1_PHY();
    fn USB1();
    fn USB1_NEEDCLK();
    fn SEC_HYPERVISOR_CALL();
    fn SEC_GPIO_INT0_IRQ0();
    fn SEC_GPIO_INT0_IRQ1();
    fn PLU();
    fn SEC_VIO();
    fn HASHCRYPT();
    fn CASER();
    fn PUF();
    fn DMA1();
    fn FLEXCOMM8();
    fn CDOG();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 61] = [
    Vector { _handler: WDT_BOD },
    Vector { _handler: DMA0 },
    Vector { _handler: GINT0 },
    Vector { _handler: GINT1 },
    Vector { _handler: PIN_INT0 },
    Vector { _handler: PIN_INT1 },
    Vector { _handler: PIN_INT2 },
    Vector { _handler: PIN_INT3 },
    Vector { _handler: UTICK0 },
    Vector { _handler: MRT0 },
    Vector { _handler: CTIMER0 },
    Vector { _handler: CTIMER1 },
    Vector { _handler: SCT0 },
    Vector { _handler: CTIMER3 },
    Vector {
        _handler: FLEXCOMM0,
    },
    Vector {
        _handler: FLEXCOMM1,
    },
    Vector {
        _handler: FLEXCOMM2,
    },
    Vector {
        _handler: FLEXCOMM3,
    },
    Vector {
        _handler: FLEXCOMM4,
    },
    Vector {
        _handler: FLEXCOMM5,
    },
    Vector {
        _handler: FLEXCOMM6,
    },
    Vector {
        _handler: FLEXCOMM7,
    },
    Vector { _handler: ADC0 },
    Vector { _reserved: 0 },
    Vector { _handler: ACMP },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: USB0_NEEDCLK,
    },
    Vector { _handler: USB0 },
    Vector { _handler: RTC },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _handler: PIN_INT4 },
    Vector { _handler: PIN_INT5 },
    Vector { _handler: PIN_INT6 },
    Vector { _handler: PIN_INT7 },
    Vector { _handler: CTIMER2 },
    Vector { _handler: CTIMER4 },
    Vector { _handler: OS_EVENT },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector { _reserved: 0 },
    Vector {
        _handler: CAN0_IRQ0,
    },
    Vector {
        _handler: CAN0_IRQ1,
    },
    Vector { _reserved: 0 },
    Vector { _handler: USB1_PHY },
    Vector { _handler: USB1 },
    Vector {
        _handler: USB1_NEEDCLK,
    },
    Vector {
        _handler: SEC_HYPERVISOR_CALL,
    },
    Vector {
        _handler: SEC_GPIO_INT0_IRQ0,
    },
    Vector {
        _handler: SEC_GPIO_INT0_IRQ1,
    },
    Vector { _handler: PLU },
    Vector { _handler: SEC_VIO },
    Vector {
        _handler: HASHCRYPT,
    },
    Vector { _handler: CASER },
    Vector { _handler: PUF },
    Vector { _reserved: 0 },
    Vector { _handler: DMA1 },
    Vector {
        _handler: FLEXCOMM8,
    },
    Vector { _handler: CDOG },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - WDT_BOD"]
    WDT_BOD = 0,
    #[doc = "1 - DMA0"]
    DMA0 = 1,
    #[doc = "2 - GINT0"]
    GINT0 = 2,
    #[doc = "3 - GINT1"]
    GINT1 = 3,
    #[doc = "4 - PIN_INT0"]
    PIN_INT0 = 4,
    #[doc = "5 - PIN_INT1"]
    PIN_INT1 = 5,
    #[doc = "6 - PIN_INT2"]
    PIN_INT2 = 6,
    #[doc = "7 - PIN_INT3"]
    PIN_INT3 = 7,
    #[doc = "8 - UTICK0"]
    UTICK0 = 8,
    #[doc = "9 - MRT0"]
    MRT0 = 9,
    #[doc = "10 - CTIMER0"]
    CTIMER0 = 10,
    #[doc = "11 - CTIMER1"]
    CTIMER1 = 11,
    #[doc = "12 - SCT0"]
    SCT0 = 12,
    #[doc = "13 - CTIMER3"]
    CTIMER3 = 13,
    #[doc = "14 - FLEXCOMM0"]
    FLEXCOMM0 = 14,
    #[doc = "15 - FLEXCOMM1"]
    FLEXCOMM1 = 15,
    #[doc = "16 - FLEXCOMM2"]
    FLEXCOMM2 = 16,
    #[doc = "17 - FLEXCOMM3"]
    FLEXCOMM3 = 17,
    #[doc = "18 - FLEXCOMM4"]
    FLEXCOMM4 = 18,
    #[doc = "19 - FLEXCOMM5"]
    FLEXCOMM5 = 19,
    #[doc = "20 - FLEXCOMM6"]
    FLEXCOMM6 = 20,
    #[doc = "21 - FLEXCOMM7"]
    FLEXCOMM7 = 21,
    #[doc = "22 - ADC0"]
    ADC0 = 22,
    #[doc = "24 - ACMP"]
    ACMP = 24,
    #[doc = "27 - USB0_NEEDCLK"]
    USB0_NEEDCLK = 27,
    #[doc = "28 - USB0"]
    USB0 = 28,
    #[doc = "29 - RTC"]
    RTC = 29,
    #[doc = "32 - PIN_INT4"]
    PIN_INT4 = 32,
    #[doc = "33 - PIN_INT5"]
    PIN_INT5 = 33,
    #[doc = "34 - PIN_INT6"]
    PIN_INT6 = 34,
    #[doc = "35 - PIN_INT7"]
    PIN_INT7 = 35,
    #[doc = "36 - CTIMER2"]
    CTIMER2 = 36,
    #[doc = "37 - CTIMER4"]
    CTIMER4 = 37,
    #[doc = "38 - OS_EVENT"]
    OS_EVENT = 38,
    #[doc = "43 - CAN0_IRQ0"]
    CAN0_IRQ0 = 43,
    #[doc = "44 - CAN0_IRQ1"]
    CAN0_IRQ1 = 44,
    #[doc = "46 - USB1_PHY"]
    USB1_PHY = 46,
    #[doc = "47 - USB1"]
    USB1 = 47,
    #[doc = "48 - USB1_NEEDCLK"]
    USB1_NEEDCLK = 48,
    #[doc = "49 - SEC_HYPERVISOR_CALL"]
    SEC_HYPERVISOR_CALL = 49,
    #[doc = "50 - SEC_GPIO_INT0_IRQ0"]
    SEC_GPIO_INT0_IRQ0 = 50,
    #[doc = "51 - SEC_GPIO_INT0_IRQ1"]
    SEC_GPIO_INT0_IRQ1 = 51,
    #[doc = "52 - PLU"]
    PLU = 52,
    #[doc = "53 - SEC_VIO"]
    SEC_VIO = 53,
    #[doc = "54 - HASHCRYPT"]
    HASHCRYPT = 54,
    #[doc = "55 - CASER"]
    CASER = 55,
    #[doc = "56 - PUF"]
    PUF = 56,
    #[doc = "58 - DMA1"]
    DMA1 = 58,
    #[doc = "59 - FLEXCOMM8"]
    FLEXCOMM8 = 59,
    #[doc = "60 - CDOG"]
    CDOG = 60,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "FLASH_CFPA"]
pub type FlashCfpa0 = crate::Periph<flash_cfpa0::RegisterBlock, 0x0003_e000>;
impl core::fmt::Debug for FlashCfpa0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashCfpa0").finish()
    }
}
#[doc = "FLASH_CFPA"]
pub mod flash_cfpa0;
#[doc = "FLASH_CFPA"]
pub type FlashCfpaScratch = crate::Periph<flash_cfpa0::RegisterBlock, 0x0003_de00>;
impl core::fmt::Debug for FlashCfpaScratch {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashCfpaScratch").finish()
    }
}
#[doc = "FLASH_CFPA"]
pub use self::flash_cfpa0 as flash_cfpa_scratch;
#[doc = "FLASH_CFPA"]
pub type FlashCfpa1 = crate::Periph<flash_cfpa0::RegisterBlock, 0x0003_e200>;
impl core::fmt::Debug for FlashCfpa1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashCfpa1").finish()
    }
}
#[doc = "FLASH_CFPA"]
pub use self::flash_cfpa0 as flash_cfpa1;
#[doc = "FLASH_CMPA"]
pub type FlashCmpa = crate::Periph<flash_cmpa::RegisterBlock, 0x0003_e400>;
impl core::fmt::Debug for FlashCmpa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashCmpa").finish()
    }
}
#[doc = "FLASH_CMPA"]
pub mod flash_cmpa;
#[doc = "FLASH_KEY_STORE"]
pub type FlashKeyStore = crate::Periph<flash_key_store::RegisterBlock, 0x0003_e600>;
impl core::fmt::Debug for FlashKeyStore {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashKeyStore").finish()
    }
}
#[doc = "FLASH_KEY_STORE"]
pub mod flash_key_store;
#[doc = "FLASH_ROMPATCH"]
pub type FlashRompatch = crate::Periph<flash_rompatch::RegisterBlock, 0x0003_ec00>;
impl core::fmt::Debug for FlashRompatch {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashRompatch").finish()
    }
}
#[doc = "FLASH_ROMPATCH"]
pub mod flash_rompatch;
#[doc = "FLASH_NMPA"]
pub type FlashNmpa = crate::Periph<flash_nmpa::RegisterBlock, 0x0003_fc00>;
impl core::fmt::Debug for FlashNmpa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashNmpa").finish()
    }
}
#[doc = "FLASH_NMPA"]
pub mod flash_nmpa;
#[doc = "SYSCON"]
pub type Syscon = crate::Periph<syscon::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for Syscon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Syscon").finish()
    }
}
#[doc = "SYSCON"]
pub mod syscon;
#[doc = "I/O pin configuration (IOCON)"]
pub type Iocon = crate::Periph<iocon::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for Iocon {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iocon").finish()
    }
}
#[doc = "I/O pin configuration (IOCON)"]
pub mod iocon;
#[doc = "Group GPIO input interrupt (GINT0/1)"]
pub type Gint0 = crate::Periph<gint0::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Gint0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gint0").finish()
    }
}
#[doc = "Group GPIO input interrupt (GINT0/1)"]
pub mod gint0;
#[doc = "Group GPIO input interrupt (GINT0/1)"]
pub type Gint1 = crate::Periph<gint0::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Gint1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gint1").finish()
    }
}
#[doc = "Group GPIO input interrupt (GINT0/1)"]
pub use self::gint0 as gint1;
#[doc = "Pin interrupt and pattern match (PINT)"]
pub type Pint = crate::Periph<pint::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Pint {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pint").finish()
    }
}
#[doc = "Pin interrupt and pattern match (PINT)"]
pub mod pint;
#[doc = "Pin interrupt and pattern match (PINT)"]
pub type Secpint = crate::Periph<pint::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Secpint {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Secpint").finish()
    }
}
#[doc = "Pin interrupt and pattern match (PINT)"]
pub use self::pint as secpint;
#[doc = "Input multiplexing (INPUT MUX)"]
pub type Inputmux = crate::Periph<inputmux::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Inputmux {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Inputmux").finish()
    }
}
#[doc = "Input multiplexing (INPUT MUX)"]
pub mod inputmux;
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub type Ctimer0 = crate::Periph<ctimer0::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Ctimer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer0").finish()
    }
}
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub mod ctimer0;
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub type Ctimer1 = crate::Periph<ctimer0::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Ctimer1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer1").finish()
    }
}
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub use self::ctimer0 as ctimer1;
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub type Ctimer2 = crate::Periph<ctimer0::RegisterBlock, 0x4002_8000>;
impl core::fmt::Debug for Ctimer2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer2").finish()
    }
}
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub use self::ctimer0 as ctimer2;
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub type Ctimer3 = crate::Periph<ctimer0::RegisterBlock, 0x4002_9000>;
impl core::fmt::Debug for Ctimer3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer3").finish()
    }
}
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub use self::ctimer0 as ctimer3;
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub type Ctimer4 = crate::Periph<ctimer0::RegisterBlock, 0x4002_a000>;
impl core::fmt::Debug for Ctimer4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ctimer4").finish()
    }
}
#[doc = "Standard counter/timers (CTIMER0 to 4)"]
pub use self::ctimer0 as ctimer4;
#[doc = "Windowed Watchdog Timer (WWDT)"]
pub type Wwdt = crate::Periph<wwdt::RegisterBlock, 0x4000_c000>;
impl core::fmt::Debug for Wwdt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Wwdt").finish()
    }
}
#[doc = "Windowed Watchdog Timer (WWDT)"]
pub mod wwdt;
#[doc = "Multi-Rate Timer (MRT)"]
pub type Mrt0 = crate::Periph<mrt0::RegisterBlock, 0x4000_d000>;
impl core::fmt::Debug for Mrt0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Mrt0").finish()
    }
}
#[doc = "Multi-Rate Timer (MRT)"]
pub mod mrt0;
#[doc = "Micro-tick Timer (UTICK)"]
pub type Utick0 = crate::Periph<utick0::RegisterBlock, 0x4000_e000>;
impl core::fmt::Debug for Utick0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Utick0").finish()
    }
}
#[doc = "Micro-tick Timer (UTICK)"]
pub mod utick0;
#[doc = "ANALOGCTRL"]
pub type Anactrl = crate::Periph<anactrl::RegisterBlock, 0x4001_3000>;
impl core::fmt::Debug for Anactrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Anactrl").finish()
    }
}
#[doc = "ANALOGCTRL"]
pub mod anactrl;
#[doc = "PMC"]
pub type Pmc = crate::Periph<pmc::RegisterBlock, 0x4002_0000>;
impl core::fmt::Debug for Pmc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pmc").finish()
    }
}
#[doc = "PMC"]
pub mod pmc;
#[doc = "system controller"]
pub type Sysctl = crate::Periph<sysctl::RegisterBlock, 0x4002_3000>;
impl core::fmt::Debug for Sysctl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sysctl").finish()
    }
}
#[doc = "system controller"]
pub mod sysctl;
#[doc = "Real-Time Clock (RTC)"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4002_c000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "Real-Time Clock (RTC)"]
pub mod rtc;
#[doc = "Synchronous OS/Event timer with Wakeup Timer"]
pub type Ostimer = crate::Periph<ostimer::RegisterBlock, 0x4002_d000>;
impl core::fmt::Debug for Ostimer {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Ostimer").finish()
    }
}
#[doc = "Synchronous OS/Event timer with Wakeup Timer"]
pub mod ostimer;
#[doc = "FLASH"]
pub type Flash = crate::Periph<flash::RegisterBlock, 0x4003_4000>;
impl core::fmt::Debug for Flash {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flash").finish()
    }
}
#[doc = "FLASH"]
pub mod flash;
#[doc = "PRINCE"]
pub type Prince = crate::Periph<prince::RegisterBlock, 0x4003_5000>;
impl core::fmt::Debug for Prince {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Prince").finish()
    }
}
#[doc = "PRINCE"]
pub mod prince;
#[doc = "Universal System Bus Physical Layer"]
pub type Usbphy = crate::Periph<usbphy::RegisterBlock, 0x4003_8000>;
impl core::fmt::Debug for Usbphy {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbphy").finish()
    }
}
#[doc = "Universal System Bus Physical Layer"]
pub mod usbphy;
#[doc = "RNG"]
pub type Rng = crate::Periph<rng::RegisterBlock, 0x4003_a000>;
impl core::fmt::Debug for Rng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rng").finish()
    }
}
#[doc = "RNG"]
pub mod rng;
#[doc = "PUFCTRL"]
pub type Puf = crate::Periph<puf::RegisterBlock, 0x4003_b000>;
impl core::fmt::Debug for Puf {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Puf").finish()
    }
}
#[doc = "PUFCTRL"]
pub mod puf;
#[doc = "PUF SRAM Control"]
pub type PufSramCtrl = crate::Periph<puf_sram_ctrl::RegisterBlock, 0x4003_b000>;
impl core::fmt::Debug for PufSramCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("PufSramCtrl").finish()
    }
}
#[doc = "PUF SRAM Control"]
pub mod puf_sram_ctrl;
#[doc = "LPC80X Programmable Logic Unit (PLU)"]
pub type Plu = crate::Periph<plu::RegisterBlock, 0x4003_d000>;
impl core::fmt::Debug for Plu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Plu").finish()
    }
}
#[doc = "LPC80X Programmable Logic Unit (PLU)"]
pub mod plu;
#[doc = "DMA controller"]
pub type Dma0 = crate::Periph<dma0::RegisterBlock, 0x4008_2000>;
impl core::fmt::Debug for Dma0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma0").finish()
    }
}
#[doc = "DMA controller"]
pub mod dma0;
#[doc = "DMA controller"]
pub type Dma1 = crate::Periph<dma0::RegisterBlock, 0x400a_7000>;
impl core::fmt::Debug for Dma1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma1").finish()
    }
}
#[doc = "DMA controller"]
pub use self::dma0 as dma1;
#[doc = "USB 2.0 Device Controller"]
pub type Usb0 = crate::Periph<usb0::RegisterBlock, 0x4008_4000>;
impl core::fmt::Debug for Usb0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usb0").finish()
    }
}
#[doc = "USB 2.0 Device Controller"]
pub mod usb0;
#[doc = "SCTimer/PWM (SCT)"]
pub type Sct0 = crate::Periph<sct0::RegisterBlock, 0x4008_5000>;
impl core::fmt::Debug for Sct0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sct0").finish()
    }
}
#[doc = "SCTimer/PWM (SCT)"]
pub mod sct0;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm0 = crate::Periph<flexcomm0::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for Flexcomm0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm0").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub mod flexcomm0;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm1 = crate::Periph<flexcomm0::RegisterBlock, 0x4008_7000>;
impl core::fmt::Debug for Flexcomm1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm1").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm1;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm2 = crate::Periph<flexcomm0::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for Flexcomm2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm2").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm2;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm3 = crate::Periph<flexcomm0::RegisterBlock, 0x4008_9000>;
impl core::fmt::Debug for Flexcomm3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm3").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm3;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm4 = crate::Periph<flexcomm0::RegisterBlock, 0x4008_a000>;
impl core::fmt::Debug for Flexcomm4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm4").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm4;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm5 = crate::Periph<flexcomm0::RegisterBlock, 0x4009_6000>;
impl core::fmt::Debug for Flexcomm5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm5").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm5;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm6 = crate::Periph<flexcomm0::RegisterBlock, 0x4009_7000>;
impl core::fmt::Debug for Flexcomm6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm6").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm6;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm7 = crate::Periph<flexcomm0::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for Flexcomm7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm7").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm7;
#[doc = "Flexcomm serial communication"]
pub type Flexcomm8 = crate::Periph<flexcomm0::RegisterBlock, 0x4009_f000>;
impl core::fmt::Debug for Flexcomm8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Flexcomm8").finish()
    }
}
#[doc = "Flexcomm serial communication"]
pub use self::flexcomm0 as flexcomm8;
#[doc = "I2C-bus interfaces"]
pub type I2c0 = crate::Periph<i2c0::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for I2c0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c0").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub mod i2c0;
#[doc = "I2C-bus interfaces"]
pub type I2c1 = crate::Periph<i2c0::RegisterBlock, 0x4008_7000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub use self::i2c0 as i2c1;
#[doc = "I2C-bus interfaces"]
pub type I2c2 = crate::Periph<i2c0::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub use self::i2c0 as i2c2;
#[doc = "I2C-bus interfaces"]
pub type I2c3 = crate::Periph<i2c0::RegisterBlock, 0x4008_9000>;
impl core::fmt::Debug for I2c3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c3").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub use self::i2c0 as i2c3;
#[doc = "I2C-bus interfaces"]
pub type I2c4 = crate::Periph<i2c0::RegisterBlock, 0x4008_a000>;
impl core::fmt::Debug for I2c4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c4").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub use self::i2c0 as i2c4;
#[doc = "I2C-bus interfaces"]
pub type I2c5 = crate::Periph<i2c0::RegisterBlock, 0x4009_6000>;
impl core::fmt::Debug for I2c5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c5").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub use self::i2c0 as i2c5;
#[doc = "I2C-bus interfaces"]
pub type I2c6 = crate::Periph<i2c0::RegisterBlock, 0x4009_7000>;
impl core::fmt::Debug for I2c6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c6").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub use self::i2c0 as i2c6;
#[doc = "I2C-bus interfaces"]
pub type I2c7 = crate::Periph<i2c0::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for I2c7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c7").finish()
    }
}
#[doc = "I2C-bus interfaces"]
pub use self::i2c0 as i2c7;
#[doc = "I2S interface"]
pub type I2s0 = crate::Periph<i2s0::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for I2s0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s0").finish()
    }
}
#[doc = "I2S interface"]
pub mod i2s0;
#[doc = "I2S interface"]
pub type I2s1 = crate::Periph<i2s0::RegisterBlock, 0x4008_7000>;
impl core::fmt::Debug for I2s1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s1").finish()
    }
}
#[doc = "I2S interface"]
pub use self::i2s0 as i2s1;
#[doc = "I2S interface"]
pub type I2s2 = crate::Periph<i2s0::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for I2s2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s2").finish()
    }
}
#[doc = "I2S interface"]
pub use self::i2s0 as i2s2;
#[doc = "I2S interface"]
pub type I2s3 = crate::Periph<i2s0::RegisterBlock, 0x4008_9000>;
impl core::fmt::Debug for I2s3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s3").finish()
    }
}
#[doc = "I2S interface"]
pub use self::i2s0 as i2s3;
#[doc = "I2S interface"]
pub type I2s4 = crate::Periph<i2s0::RegisterBlock, 0x4008_a000>;
impl core::fmt::Debug for I2s4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s4").finish()
    }
}
#[doc = "I2S interface"]
pub use self::i2s0 as i2s4;
#[doc = "I2S interface"]
pub type I2s5 = crate::Periph<i2s0::RegisterBlock, 0x4009_6000>;
impl core::fmt::Debug for I2s5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s5").finish()
    }
}
#[doc = "I2S interface"]
pub use self::i2s0 as i2s5;
#[doc = "I2S interface"]
pub type I2s6 = crate::Periph<i2s0::RegisterBlock, 0x4009_7000>;
impl core::fmt::Debug for I2s6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s6").finish()
    }
}
#[doc = "I2S interface"]
pub use self::i2s0 as i2s6;
#[doc = "I2S interface"]
pub type I2s7 = crate::Periph<i2s0::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for I2s7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2s7").finish()
    }
}
#[doc = "I2S interface"]
pub use self::i2s0 as i2s7;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi0 = crate::Periph<spi0::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for Spi0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi0").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub mod spi0;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi1 = crate::Periph<spi0::RegisterBlock, 0x4008_7000>;
impl core::fmt::Debug for Spi1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi1").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi1;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi2 = crate::Periph<spi0::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for Spi2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi2").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi2;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi3 = crate::Periph<spi0::RegisterBlock, 0x4008_9000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi3;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi4 = crate::Periph<spi0::RegisterBlock, 0x4008_a000>;
impl core::fmt::Debug for Spi4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi4").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi4;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi5 = crate::Periph<spi0::RegisterBlock, 0x4009_6000>;
impl core::fmt::Debug for Spi5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi5").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi5;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi6 = crate::Periph<spi0::RegisterBlock, 0x4009_7000>;
impl core::fmt::Debug for Spi6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi6").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi6;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi7 = crate::Periph<spi0::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for Spi7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi7").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi7;
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub type Spi8 = crate::Periph<spi0::RegisterBlock, 0x4009_f000>;
impl core::fmt::Debug for Spi8 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi8").finish()
    }
}
#[doc = "Serial Peripheral Interfaces (SPI)"]
pub use self::spi0 as spi8;
#[doc = "USARTs"]
pub type Usart0 = crate::Periph<usart0::RegisterBlock, 0x4008_6000>;
impl core::fmt::Debug for Usart0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart0").finish()
    }
}
#[doc = "USARTs"]
pub mod usart0;
#[doc = "USARTs"]
pub type Usart1 = crate::Periph<usart0::RegisterBlock, 0x4008_7000>;
impl core::fmt::Debug for Usart1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart1").finish()
    }
}
#[doc = "USARTs"]
pub use self::usart0 as usart1;
#[doc = "USARTs"]
pub type Usart2 = crate::Periph<usart0::RegisterBlock, 0x4008_8000>;
impl core::fmt::Debug for Usart2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart2").finish()
    }
}
#[doc = "USARTs"]
pub use self::usart0 as usart2;
#[doc = "USARTs"]
pub type Usart3 = crate::Periph<usart0::RegisterBlock, 0x4008_9000>;
impl core::fmt::Debug for Usart3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart3").finish()
    }
}
#[doc = "USARTs"]
pub use self::usart0 as usart3;
#[doc = "USARTs"]
pub type Usart4 = crate::Periph<usart0::RegisterBlock, 0x4008_a000>;
impl core::fmt::Debug for Usart4 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart4").finish()
    }
}
#[doc = "USARTs"]
pub use self::usart0 as usart4;
#[doc = "USARTs"]
pub type Usart5 = crate::Periph<usart0::RegisterBlock, 0x4009_6000>;
impl core::fmt::Debug for Usart5 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart5").finish()
    }
}
#[doc = "USARTs"]
pub use self::usart0 as usart5;
#[doc = "USARTs"]
pub type Usart6 = crate::Periph<usart0::RegisterBlock, 0x4009_7000>;
impl core::fmt::Debug for Usart6 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart6").finish()
    }
}
#[doc = "USARTs"]
pub use self::usart0 as usart6;
#[doc = "USARTs"]
pub type Usart7 = crate::Periph<usart0::RegisterBlock, 0x4009_8000>;
impl core::fmt::Debug for Usart7 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart7").finish()
    }
}
#[doc = "USARTs"]
pub use self::usart0 as usart7;
#[doc = "General Purpose I/O (GPIO)"]
pub type Gpio = crate::Periph<gpio::RegisterBlock, 0x4008_c000>;
impl core::fmt::Debug for Gpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio").finish()
    }
}
#[doc = "General Purpose I/O (GPIO)"]
pub mod gpio;
#[doc = "USB1 High-speed Device Controller"]
pub type Usbhsd = crate::Periph<usbhsd::RegisterBlock, 0x4009_4000>;
impl core::fmt::Debug for Usbhsd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbhsd").finish()
    }
}
#[doc = "USB1 High-speed Device Controller"]
pub mod usbhsd;
#[doc = "CRC engine"]
pub type CrcEngine = crate::Periph<crc_engine::RegisterBlock, 0x4009_5000>;
impl core::fmt::Debug for CrcEngine {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CrcEngine").finish()
    }
}
#[doc = "CRC engine"]
pub mod crc_engine;
#[doc = "MCU Debugger Mailbox"]
pub type Dbgmailbox = crate::Periph<dbgmailbox::RegisterBlock, 0x4009_c000>;
impl core::fmt::Debug for Dbgmailbox {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dbgmailbox").finish()
    }
}
#[doc = "MCU Debugger Mailbox"]
pub mod dbgmailbox;
#[doc = "Controller Area Network Flexible Data (CAN FD)"]
pub type Can0 = crate::Periph<can0::RegisterBlock, 0x4009_d000>;
impl core::fmt::Debug for Can0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Can0").finish()
    }
}
#[doc = "Controller Area Network Flexible Data (CAN FD)"]
pub mod can0;
#[doc = "ADC"]
pub type Adc0 = crate::Periph<adc0::RegisterBlock, 0x400a_0000>;
impl core::fmt::Debug for Adc0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc0").finish()
    }
}
#[doc = "ADC"]
pub mod adc0;
#[doc = "CDOG"]
pub type Cdog = crate::Periph<cdog::RegisterBlock, 0x400a_1000>;
impl core::fmt::Debug for Cdog {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Cdog").finish()
    }
}
#[doc = "CDOG"]
pub mod cdog;
#[doc = "USB0 Full-speed Host controller"]
pub type Usbfsh = crate::Periph<usbfsh::RegisterBlock, 0x400a_2000>;
impl core::fmt::Debug for Usbfsh {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbfsh").finish()
    }
}
#[doc = "USB0 Full-speed Host controller"]
pub mod usbfsh;
#[doc = "USB1 High-speed Host Controller"]
pub type Usbhsh = crate::Periph<usbhsh::RegisterBlock, 0x400a_3000>;
impl core::fmt::Debug for Usbhsh {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usbhsh").finish()
    }
}
#[doc = "USB1 High-speed Host Controller"]
pub mod usbhsh;
#[doc = "Hash-Crypt peripheral"]
pub type Hashcrypt = crate::Periph<hashcrypt::RegisterBlock, 0x400a_4000>;
impl core::fmt::Debug for Hashcrypt {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Hashcrypt").finish()
    }
}
#[doc = "Hash-Crypt peripheral"]
pub mod hashcrypt;
#[doc = "CASPER"]
pub type Casper = crate::Periph<casper::RegisterBlock, 0x400a_5000>;
impl core::fmt::Debug for Casper {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Casper").finish()
    }
}
#[doc = "CASPER"]
pub mod casper;
#[doc = "General Purpose I/O (GPIO)"]
pub type Secgpio = crate::Periph<secgpio::RegisterBlock, 0x400a_8000>;
impl core::fmt::Debug for Secgpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Secgpio").finish()
    }
}
#[doc = "General Purpose I/O (GPIO)"]
pub mod secgpio;
#[doc = "AHB secure controller"]
pub type AhbSecureCtrl = crate::Periph<ahb_secure_ctrl::RegisterBlock, 0x400a_c000>;
impl core::fmt::Debug for AhbSecureCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("AhbSecureCtrl").finish()
    }
}
#[doc = "AHB secure controller"]
pub mod ahb_secure_ctrl;
#[doc = "no description available"]
pub type ScnScb = crate::Periph<scn_scb::RegisterBlock, 0xe000_e000>;
impl core::fmt::Debug for ScnScb {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("ScnScb").finish()
    }
}
#[doc = "no description available"]
pub mod scn_scb;
#[doc = "no description available"]
pub type Sau = crate::Periph<sau::RegisterBlock, 0xe000_edd0>;
impl core::fmt::Debug for Sau {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Sau").finish()
    }
}
#[doc = "no description available"]
pub mod sau;
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "FLASH_CFPA0"]
    pub flash_cfpa0: FlashCfpa0,
    #[doc = "FLASH_CFPA_SCRATCH"]
    pub flash_cfpa_scratch: FlashCfpaScratch,
    #[doc = "FLASH_CFPA1"]
    pub flash_cfpa1: FlashCfpa1,
    #[doc = "FLASH_CMPA"]
    pub flash_cmpa: FlashCmpa,
    #[doc = "FLASH_KEY_STORE"]
    pub flash_key_store: FlashKeyStore,
    #[doc = "FLASH_ROMPATCH"]
    pub flash_rompatch: FlashRompatch,
    #[doc = "FLASH_NMPA"]
    pub flash_nmpa: FlashNmpa,
    #[doc = "SYSCON"]
    pub syscon: Syscon,
    #[doc = "IOCON"]
    pub iocon: Iocon,
    #[doc = "GINT0"]
    pub gint0: Gint0,
    #[doc = "GINT1"]
    pub gint1: Gint1,
    #[doc = "PINT"]
    pub pint: Pint,
    #[doc = "SECPINT"]
    pub secpint: Secpint,
    #[doc = "INPUTMUX"]
    pub inputmux: Inputmux,
    #[doc = "CTIMER0"]
    pub ctimer0: Ctimer0,
    #[doc = "CTIMER1"]
    pub ctimer1: Ctimer1,
    #[doc = "CTIMER2"]
    pub ctimer2: Ctimer2,
    #[doc = "CTIMER3"]
    pub ctimer3: Ctimer3,
    #[doc = "CTIMER4"]
    pub ctimer4: Ctimer4,
    #[doc = "WWDT"]
    pub wwdt: Wwdt,
    #[doc = "MRT0"]
    pub mrt0: Mrt0,
    #[doc = "UTICK0"]
    pub utick0: Utick0,
    #[doc = "ANACTRL"]
    pub anactrl: Anactrl,
    #[doc = "PMC"]
    pub pmc: Pmc,
    #[doc = "SYSCTL"]
    pub sysctl: Sysctl,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "OSTIMER"]
    pub ostimer: Ostimer,
    #[doc = "FLASH"]
    pub flash: Flash,
    #[doc = "PRINCE"]
    pub prince: Prince,
    #[doc = "USBPHY"]
    pub usbphy: Usbphy,
    #[doc = "RNG"]
    pub rng: Rng,
    #[doc = "PUF"]
    pub puf: Puf,
    #[doc = "PUF_SRAM_CTRL"]
    pub puf_sram_ctrl: PufSramCtrl,
    #[doc = "PLU"]
    pub plu: Plu,
    #[doc = "DMA0"]
    pub dma0: Dma0,
    #[doc = "DMA1"]
    pub dma1: Dma1,
    #[doc = "USB0"]
    pub usb0: Usb0,
    #[doc = "SCT0"]
    pub sct0: Sct0,
    #[doc = "FLEXCOMM0"]
    pub flexcomm0: Flexcomm0,
    #[doc = "FLEXCOMM1"]
    pub flexcomm1: Flexcomm1,
    #[doc = "FLEXCOMM2"]
    pub flexcomm2: Flexcomm2,
    #[doc = "FLEXCOMM3"]
    pub flexcomm3: Flexcomm3,
    #[doc = "FLEXCOMM4"]
    pub flexcomm4: Flexcomm4,
    #[doc = "FLEXCOMM5"]
    pub flexcomm5: Flexcomm5,
    #[doc = "FLEXCOMM6"]
    pub flexcomm6: Flexcomm6,
    #[doc = "FLEXCOMM7"]
    pub flexcomm7: Flexcomm7,
    #[doc = "FLEXCOMM8"]
    pub flexcomm8: Flexcomm8,
    #[doc = "I2C0"]
    pub i2c0: I2c0,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "I2C3"]
    pub i2c3: I2c3,
    #[doc = "I2C4"]
    pub i2c4: I2c4,
    #[doc = "I2C5"]
    pub i2c5: I2c5,
    #[doc = "I2C6"]
    pub i2c6: I2c6,
    #[doc = "I2C7"]
    pub i2c7: I2c7,
    #[doc = "I2S0"]
    pub i2s0: I2s0,
    #[doc = "I2S1"]
    pub i2s1: I2s1,
    #[doc = "I2S2"]
    pub i2s2: I2s2,
    #[doc = "I2S3"]
    pub i2s3: I2s3,
    #[doc = "I2S4"]
    pub i2s4: I2s4,
    #[doc = "I2S5"]
    pub i2s5: I2s5,
    #[doc = "I2S6"]
    pub i2s6: I2s6,
    #[doc = "I2S7"]
    pub i2s7: I2s7,
    #[doc = "SPI0"]
    pub spi0: Spi0,
    #[doc = "SPI1"]
    pub spi1: Spi1,
    #[doc = "SPI2"]
    pub spi2: Spi2,
    #[doc = "SPI3"]
    pub spi3: Spi3,
    #[doc = "SPI4"]
    pub spi4: Spi4,
    #[doc = "SPI5"]
    pub spi5: Spi5,
    #[doc = "SPI6"]
    pub spi6: Spi6,
    #[doc = "SPI7"]
    pub spi7: Spi7,
    #[doc = "SPI8"]
    pub spi8: Spi8,
    #[doc = "USART0"]
    pub usart0: Usart0,
    #[doc = "USART1"]
    pub usart1: Usart1,
    #[doc = "USART2"]
    pub usart2: Usart2,
    #[doc = "USART3"]
    pub usart3: Usart3,
    #[doc = "USART4"]
    pub usart4: Usart4,
    #[doc = "USART5"]
    pub usart5: Usart5,
    #[doc = "USART6"]
    pub usart6: Usart6,
    #[doc = "USART7"]
    pub usart7: Usart7,
    #[doc = "GPIO"]
    pub gpio: Gpio,
    #[doc = "USBHSD"]
    pub usbhsd: Usbhsd,
    #[doc = "CRC_ENGINE"]
    pub crc_engine: CrcEngine,
    #[doc = "DBGMAILBOX"]
    pub dbgmailbox: Dbgmailbox,
    #[doc = "CAN0"]
    pub can0: Can0,
    #[doc = "ADC0"]
    pub adc0: Adc0,
    #[doc = "CDOG"]
    pub cdog: Cdog,
    #[doc = "USBFSH"]
    pub usbfsh: Usbfsh,
    #[doc = "USBHSH"]
    pub usbhsh: Usbhsh,
    #[doc = "HASHCRYPT"]
    pub hashcrypt: Hashcrypt,
    #[doc = "CASPER"]
    pub casper: Casper,
    #[doc = "SECGPIO"]
    pub secgpio: Secgpio,
    #[doc = "AHB_SECURE_CTRL"]
    pub ahb_secure_ctrl: AhbSecureCtrl,
    #[doc = "SCnSCB"]
    pub scn_scb: ScnScb,
    #[doc = "SAU"]
    pub sau: Sau,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            flash_cfpa0: FlashCfpa0::steal(),
            flash_cfpa_scratch: FlashCfpaScratch::steal(),
            flash_cfpa1: FlashCfpa1::steal(),
            flash_cmpa: FlashCmpa::steal(),
            flash_key_store: FlashKeyStore::steal(),
            flash_rompatch: FlashRompatch::steal(),
            flash_nmpa: FlashNmpa::steal(),
            syscon: Syscon::steal(),
            iocon: Iocon::steal(),
            gint0: Gint0::steal(),
            gint1: Gint1::steal(),
            pint: Pint::steal(),
            secpint: Secpint::steal(),
            inputmux: Inputmux::steal(),
            ctimer0: Ctimer0::steal(),
            ctimer1: Ctimer1::steal(),
            ctimer2: Ctimer2::steal(),
            ctimer3: Ctimer3::steal(),
            ctimer4: Ctimer4::steal(),
            wwdt: Wwdt::steal(),
            mrt0: Mrt0::steal(),
            utick0: Utick0::steal(),
            anactrl: Anactrl::steal(),
            pmc: Pmc::steal(),
            sysctl: Sysctl::steal(),
            rtc: Rtc::steal(),
            ostimer: Ostimer::steal(),
            flash: Flash::steal(),
            prince: Prince::steal(),
            usbphy: Usbphy::steal(),
            rng: Rng::steal(),
            puf: Puf::steal(),
            puf_sram_ctrl: PufSramCtrl::steal(),
            plu: Plu::steal(),
            dma0: Dma0::steal(),
            dma1: Dma1::steal(),
            usb0: Usb0::steal(),
            sct0: Sct0::steal(),
            flexcomm0: Flexcomm0::steal(),
            flexcomm1: Flexcomm1::steal(),
            flexcomm2: Flexcomm2::steal(),
            flexcomm3: Flexcomm3::steal(),
            flexcomm4: Flexcomm4::steal(),
            flexcomm5: Flexcomm5::steal(),
            flexcomm6: Flexcomm6::steal(),
            flexcomm7: Flexcomm7::steal(),
            flexcomm8: Flexcomm8::steal(),
            i2c0: I2c0::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            i2c3: I2c3::steal(),
            i2c4: I2c4::steal(),
            i2c5: I2c5::steal(),
            i2c6: I2c6::steal(),
            i2c7: I2c7::steal(),
            i2s0: I2s0::steal(),
            i2s1: I2s1::steal(),
            i2s2: I2s2::steal(),
            i2s3: I2s3::steal(),
            i2s4: I2s4::steal(),
            i2s5: I2s5::steal(),
            i2s6: I2s6::steal(),
            i2s7: I2s7::steal(),
            spi0: Spi0::steal(),
            spi1: Spi1::steal(),
            spi2: Spi2::steal(),
            spi3: Spi3::steal(),
            spi4: Spi4::steal(),
            spi5: Spi5::steal(),
            spi6: Spi6::steal(),
            spi7: Spi7::steal(),
            spi8: Spi8::steal(),
            usart0: Usart0::steal(),
            usart1: Usart1::steal(),
            usart2: Usart2::steal(),
            usart3: Usart3::steal(),
            usart4: Usart4::steal(),
            usart5: Usart5::steal(),
            usart6: Usart6::steal(),
            usart7: Usart7::steal(),
            gpio: Gpio::steal(),
            usbhsd: Usbhsd::steal(),
            crc_engine: CrcEngine::steal(),
            dbgmailbox: Dbgmailbox::steal(),
            can0: Can0::steal(),
            adc0: Adc0::steal(),
            cdog: Cdog::steal(),
            usbfsh: Usbfsh::steal(),
            usbhsh: Usbhsh::steal(),
            hashcrypt: Hashcrypt::steal(),
            casper: Casper::steal(),
            secgpio: Secgpio::steal(),
            ahb_secure_ctrl: AhbSecureCtrl::steal(),
            scn_scb: ScnScb::steal(),
            sau: Sau::steal(),
        }
    }
}
